name: "Deploy"

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: rajpal-se/configure-ssh-credentials@v1
        id: configure_ssh
        with:
          key: ${{ secrets.SSH_KEY }}
          hostname: ${{ secrets.HOSTNAME }}

      - uses: ./
        with:
          aws-account-number: ${{ secrets.AWS_ACCOUNT_NUMBER }}
          aws-ecr-region: ${{ secrets.AWS_ECR_REGION }}
          aws-ecr-repository: ${{ secrets.AWS_ECR_REPOSITORY }}
          app-container-name: ${{ secrets.APP_CONTAINER_NAME }}
          app-port-mapping: ${{ secrets.APP_PORT_MAPPING }}
          app-env-file: ${{ secrets.APP_ENV_FILE }}
          app-conatiner-ip: ${{ secrets.APP_CONTAINER_IP }}
          app-docker-run-options: "--label MyLabel"
